### ISSUE TITLE
How to use Django-Netfields with Django packages requiring a custom manager

### ISSUE THREAD

**Issue by oza4h07** [jimfunk/django-postgresql-netfields#107]
Hello,

Some Django packages like Django-Polymorphic make use of custom managers.

As Django-Netfields also requires use of NetManager custom manager, one way to satisfy multiple requirements
is to have several managers and use appropriate one, depending on circumstances.

`from netfields import NetManager, InetAddressField
from Foo import FooManager, FooModel

class PersonManager(FooManager):
    def get_by_natural_key(self, first_name, last_name):
        return self.get(first_name=first_name, last_name=last_name)

class Person(FooModel):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    inet = InetAddressField()

    objects = PersonManager()
    objects_netfields = NetManager()

n1 = IPv4Network('192.168.1.0/24')
o1 = Person.objects.get(last_name='Doe')
o2 = Person.objects_netfields.get(inet__net_contained_or_equal=n1)`

Is there a way to avoid having several managers ?
I was thinking of something like bellow but any alternative would be welcome.

`from netfields import NetManager, InetAddressField, Whatever
from Foo import FooManager, FooModel

class PersonManager(FooManager, Whatever):
    def get_by_natural_key(self, first_name, last_name):
        return self.get(first_name=first_name, last_name=last_name)

class Person(FooModel):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    inet = InetAddressField()

    objects = PersonManager()

n1 = IPv4Network('192.168.1.0/24')
o1 = Person.objects.get(last_name='Doe')
o2 = Person.objects.get(inet__net_contained_or_equal=n1)`

Thoughts ? Suggestions ?

Best regards

**Comment by higherorderfunctor** [comment]
I would say multiple inheritance of managers is an anti-pattern in the current django design.   Due to method resolution order (MRO) for multiple inheritance, if both managers override the same method, they won't be composed.  In other words, only the method on the first base class will be called.  That is not to say you can't do `class PersonManager(FooManager, Whatever)`, but for every method defined in both managers, you would have manually compose the two results from each manager.  This involves inspecting the code of each respectively and figuring out how to compose the results.

This is not too hard for this particular library as the manager only [overrides one method](https://github.com/jimfunk/django-postgresql-netfields/blob/master/netfields/managers.py), but if this library added additional override methods in later versions, it could be a breaking change as you would have to add in additional manual compositions to compensate.

In summary, multiple managers is the preferred design pattern.  That said, you can give them better names than `objects_*`.  The [official django documentation](https://docs.djangoproject.com/en/3.1/topics/db/managers/#modifying-a-manager-s-initial-queryset) does just that:

```python
class AuthorManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(role='A')

class EditorManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(role='E')

class Person(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    role = models.CharField(max_length=1, choices=[('A', _('Author')), ('E', _('Editor'))])
    people = models.Manager()
    authors = AuthorManager()
    editors = EditorManager()
```

**Comment by jimfunk** [comment]
Ideally, there would be no manager at all, but Django behaves very badly in some circumstances, which results in consuming all of your memory and CPU when working with IPv6 networks or large IPv4 networks.

Meanwhile, the manager is designed to work appropriately even when multiple inheritance is used. As per Django's design, it is up to the application whether to implement multiple inheritance or separate managers and to account for any potential incompatibilities.
