### ISSUE TITLE
Python field type is str instead of ipaddress.ip_address

### ISSUE THREAD

**Issue by h1nk** [jimfunk/django-postgresql-netfields#89]
I have a model something like [this](https://github.com/insurgency/django-postgresql-netfields/blob/master/test/models.py#L107-L113) that makes use of a `InetAddressField`. When referencing the field from a model method, i.e. `self.field` it returns a `str` instead of an `IPv4Address` instance. Wouldn't the expected behavior be to return a type of `ipaddress.ip_address` like the README says? [Here's a crude unittest](https://github.com/insurgency/django-postgresql-netfields/blob/master/test/tests/test_sql_fields.py#L637-L641) I wrote that exhibits this behavior (causes a `AttributeError: 'str' object has no attribute 'is_loopback'` error).

**Comment by jimfunk** [comment]
This is due to a behaviour change in Django 1.10. The to_python() method that converts the string to an ipaddress type no longer gets called on assignment. If you saved it and loaded the object from the database, the conversion will actually occur.

If you want the ipaddress types on unsaved models, in case you are using pre/post save hooks, it's best to ensure you assign them as the expected types. If you are using Django REST Framework, and you use the field types included in this project, the fields will have the correct type since they are converted at validation time before the object is created or updated.
